services:
  app:
    build: .
    container_name: exam6lock-app
    ports:
      - "9090:80"
    volumes:
      - .:/var/www/html:z
    depends_on:
      - db
      - redis
    environment:
      REDIS_HOST: redis
      DB_HOST: db
      DB_USER: root
      DB_PASS: rootpass
      DB_NAME: ujian_online
      TZ: Asia/Jakarta
    networks:
      - exam6lock-net
    restart: unless-stopped


  redis:
    image: docker.io/library/redis:7-alpine
    container_name: exam6lock-redis
    command: redis-server --appendonly no --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - exam6lock-net
    restart: unless-stopped


  db:
    image: docker.io/library/mysql:8.0
    container_name: exam6lock-db
    command: >
      --max_connections=500
      --innodb_buffer_pool_size=4G
      --innodb_log_file_size=1G
      --innodb_flush_log_at_trx_commit=2
      --wait_timeout=180
      --interactive_timeout=180
      --thread_cache_size=100
      --tmp_table_size=256M
      --max_heap_table_size=256M
      --table_open_cache=4000
      --sort_buffer_size=4M
      --join_buffer_size=4M
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ujian_online
      MYSQL_USER: user
      MYSQL_PASSWORD: pass123
      TZ: Asia/Jakarta
    ports:
      - "3313:3306"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d:ro
      - exam6lock-dbdata:/var/lib/mysql:z
    networks:
      - exam6lock-net
    restart: unless-stopped


  phpmyadmin:
    image: docker.io/library/phpmyadmin:latest
    container_name: exam6lock-pma
    ports:
      - "9091:80"
    environment:
      PMA_HOST: db
      PMA_ARBITRARY: 1
    depends_on:
      - db
    networks:
      - exam6lock-net
    restart: unless-stopped

volumes:
  exam6lock-dbdata:

networks:
  exam6lock-net:
    driver: bridge
